# filepath: .github/workflows/ci.yml

on:
  push:
    paths:
      - 'src/**'
      - 'package.json'
      - 'yarn.lock'
      - '.github/workflows/ci.yml'

jobs:
  run-ci:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Checkout repository (os: ${{ matrix.os }})
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Needed for version history

      - name: Setup Node.js (os: ${{ matrix.os }})
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
          cache: 'yarn'

      - name: Install dependencies (os: ${{ matrix.os }})
        run: yarn install 

      - name: Build extension (os: ${{ matrix.os }})
        run: yarn run compile

      - name: Run linting (os: ${{ matrix.os }})
        run: yarn run lint
        
      - name: Verify CHANGELOG format (os: ${{ matrix.os }})
        run: |
          # Check if CHANGELOG.md exists and has correct format
          if [ ! -f CHANGELOG.md ]; then
            echo "::error::CHANGELOG.md file not found"
            exit 1
          fi
          
          # Check for Change Log header
          if ! grep -q "^# Change Log" CHANGELOG.md; then
            echo "::error::CHANGELOG.md is missing the '# Change Log' header"
            exit 1
          fi
          
          # Check for at least one version entry with correct format
          if ! grep -q "^## \[[0-9]\+\.[0-9]\+\.[0-9]\+\] - [0-9]\{4\}-[0-9]\{2\}-[0-9]\{2\}" CHANGELOG.md; then
            echo "::error::CHANGELOG.md doesn't contain any properly formatted version entries. Expected format: '## [x.y.z] - YYYY-MM-DD'"
            exit 1
          fi
          
          echo "CHANGELOG.md format verification passed!"
